CREATE DATABASE IF NOT EXISTS user_db;
USE user_db;

DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    full_name VARCHAR(100),
    phone VARCHAR(20),
    balance DECIMAL(10,2) DEFAULT 0.00,
    role VARCHAR(10) NOT NULL DEFAULT 'USER'  -- Đổi từ ENUM thành VARCHAR
);
